spring:
  application:
    name: betterreads
  security:
      oauth2:
        client:
          registration:
            github:
              client-id: <id>
              client-secret: <secret>
  data:
    cassandra:
      keyspace-name: <keyspace>
      username: <username>
      password: <password>
      schema-action: create-if-not-exists
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s

datadump:
  location:
    author: <author_file>
    work: <work_file>

datastax.astra:
    secure-connect-bundle: secure-connect-bettereads.zip

astra.db:
    id: <id>
    region: <region>
    keyspace: <keyspace>
    token: <token>